// Nexus Portal v2.4.1 — built 2024-03-15T09:12:44Z
// Do not edit this file directly — generated by Vite 4.x
//# sourceMappingURL=app.js.map
"use strict";

// ── Finding #3: hardcoded JWT secret baked into the bundle ──────────────────
// (In real life this surfaces in the source map; here it's visible in both)
const _JWT_SECRET = "nexus-jwt-hs256-pr0d-k3y-2024!";

// ── Finding #4: all API routes hardcoded including undocumented ones ─────────
const ROUTES = {
  login:        "/api/v1/auth/login",
  profile:      "/api/v1/users/me",
  users:        "/api/v1/users",
  adminUsers:   "/api/v1/admin/users",    // admin only
  adminFlag:    "/api/v1/admin/flag",     // admin only
  debug:        "/api/v1/debug/dump",     // TODO: remove before prod — SEC-388
};

// ── Finding #5: client-side role check ───────────────────────────────────────
// Role is read from the JWT payload WITHOUT verifying the signature.
// Attacker can base64-decode, modify role:"admin", re-encode, swap the payload.
function _parseToken(token) {
  try {
    const payload = JSON.parse(atob(token.split(".")[1]));
    // Finding #6: debug console.log left in
    console.log("[Nexus] token payload:", payload);
    return payload;
  } catch(e) { return null; }
}

function _getUser() {
  const t = localStorage.getItem("nexus_token");
  if (!t) return null;
  return _parseToken(t);
}

function _isAdmin() {
  const u = _getUser();
  // Finding #5: role check is purely client-side — backend also checks,
  // but the admin UI sections are gated only by this function.
  return u && u.role === "admin";
}

// ── App object ───────────────────────────────────────────────────────────────
const App = {
  async login() {
    const username = document.getElementById("inp-user").value;
    const password = document.getElementById("inp-pass").value;
    try {
      const r = await fetch(ROUTES.login, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
      });
      const data = await r.json();
      if (!r.ok) {
        document.getElementById("login-err").textContent = data.error || "Login failed";
        return;
      }
      localStorage.setItem("nexus_token", data.token);
      // Finding #6: token logged to console
      console.log("[Nexus] Logged in, token:", data.token);
      this.showDashboard();
    } catch(e) {
      document.getElementById("login-err").textContent = "Network error";
    }
  },

  showDashboard() {
    const user = _getUser();
    if (!user) { this.logout(); return; }
    document.getElementById("view-login").classList.add("d-none");
    document.getElementById("view-dashboard").classList.remove("d-none");
    document.getElementById("nav-user").textContent = `${user.username} (${user.role})`;
    document.getElementById("dashboard-content").innerHTML =
      `<p class="text-muted">Welcome back, <strong>${user.username}</strong>.</p>
       <p>Environment: <code>${window._env.APP_VERSION}</code> on <code>${window._env.AWS_REGION}</code></p>`;
    // Finding #5: show admin UI based on client-side check only
    if (_isAdmin()) {
      document.getElementById("admin-section").classList.remove("d-none");
    }
  },

  async loadAdminFlag() {
    const token = localStorage.getItem("nexus_token");
    const r = await fetch(ROUTES.adminFlag, {
      headers: { "Authorization": "Bearer " + token },
    });
    const data = await r.json();
    document.getElementById("dashboard-content").innerHTML =
      `<div class="alert alert-success"><strong>Flag:</strong> ${data.flag || data.error}</div>`;
  },

  logout() {
    localStorage.removeItem("nexus_token");
    location.reload();
  },
};

// Auto-restore session on load
document.addEventListener("DOMContentLoaded", () => {
  if (localStorage.getItem("nexus_token") && _getUser()) {
    App.showDashboard();
  }
});
