// config.js — CorpHQ Nexus Portal runtime configuration
// Generated by CI pipeline — DO NOT EDIT MANUALLY
// TODO: audit flagged this file in SEC-441, move secrets to Vault before Q3
window._env = {
  APP_NAME:            "Nexus Portal",
  APP_VERSION:         "2.4.1",
  API_BASE:            "/api/v1",
  INTERNAL_API_URL:    "http://internal-api.corphq.local:8080",
  METRICS_URL:         "http://prometheus.corphq.local:9090",
  FEATURE_FLAGS_URL:   "http://launchdarkly.corphq.local/flags",

  // Stripe publishable key (prod) — finding: wrong key type, this is SECRET
  STRIPE_SECRET_KEY:   "sk_live_LAB_EXAMPLE_KEY_vuln_machines",

  // Sentry DSN leaks org slug + project id
  SENTRY_DSN:          "https://a1b2c3d4e5f6@o123456.ingest.sentry.io/789012",

  // Internal service API key — used for server-to-server calls, should NOT be here
  INTERNAL_API_KEY:    "ik-prod-7f3a2b1c9d4e5f6a8b9c0d1e2f3a4b5c",

  // AWS region hint
  S3_BUCKET:           "corphq-user-uploads-prod",
  AWS_REGION:          "eu-west-1",
};
